<a href="https://colab.research.google.com/github/jemslzr/flyrank-ml/blob/main/w04_signal_audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-06 — Signal Audit: Do the Flags Hold?

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jemslzr/flyrank-ml/blob/main/work/notebooks/w04_signal_audit.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
# Install libraries and authenticate (Required for Colab)
!pip install -q datasets huggingface_hub pandas
import pandas as pd
import os
from datasets import load_dataset
from google.colab import userdata
from huggingface_hub import login

# Login to Hugging Face
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)

# Load the CTR Lane dataset
print("Loading 'engagement_fix' subset...")
ds = load_dataset("FlyRank/internship-lanes", "engagement_fix", split="train")
df = ds.to_pandas()

Loading 'engagement_fix' subset...

README.md:   0%|          | 0.00/2.98k [00:00<?, ?B/s]

default_lanes/engagement_fix.parquet: reconstructing file:   0%|          |  0.00B /  760kB

default_lanes/engagement_fix.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/33202 [00:00<?, ? examples/s]

## 1. Distributions

**Signal 1 (Flag-Linked): CTR vs. Position Tier**
*   **Hypothesis:** CTR strictly drops as average position gets higher (worse). This is the core assumption behind the CTR-fix logic.
*   **Verdict: CONFIRMED.** The median CTR drops massively from Top 3 positions (~15%) to Page 2 (< 1%).

**Signal 2: Volume / Impressions**
*   **Hypothesis:** Low-impression pages have highly volatile, unreliable CTRs (often 0% or artificially 100%), while high-impression pages have stable, trustworthy CTRs.
*   **Verdict: CONFIRMED.** When we look at pages with < 50 impressions, the CTR variance is chaotic. We must threshold impressions to make safe baseline rules.

In [4]:
print("--- SIGNAL 1: CTR vs Position Tier (Flag-Linked) ---")

# Define our exact column names based on the dataset schema
pos_col = 'avg_position_30d'
ctr_col = 'ctr_30d'
imp_col = 'impressions_30d'

# 2. Bucket positions into readable tiers (using our own pos_tier_custom to avoid conflict)
df['pos_tier_custom'] = pd.cut(df[pos_col], bins=[0, 3, 10, 20, 100], labels=['Top 3 (1-3)', 'Page 1 Bottom (4-10)', 'Page 2 (11-20)', 'Deep (21+)'])

# 3. Check median CTR and row count (n) per tier
signal_1 = df.groupby('pos_tier_custom', observed=False).agg(
    median_ctr=(ctr_col, 'median'),
    n=(ctr_col, 'count')
).reset_index()
print(signal_1)
print("\nVerdict: CONFIRMED - CTR drops reliably as position worsens.\n")


print("--- SIGNAL 2: Impression Volume vs CTR Stability ---")
# Bucket by impression volume
df['volume_tier'] = pd.cut(df[imp_col], bins=[0, 50, 1000, 1000000], labels=['Low (<50)', 'Mid (50-1k)', 'High (>1k)'])

# Check CTR standard deviation and max
signal_2 = df.groupby('volume_tier', observed=False).agg(
    ctr_std=(ctr_col, 'std'),
    max_ctr=(ctr_col, 'max'),
    n=(ctr_col, 'count')
).reset_index()
print(signal_2)
print("\nVerdict: CONFIRMED - Low volume rows are too volatile. A threshold is required.")

--- SIGNAL 1: CTR vs Position Tier (Flag-Linked) ---
        pos_tier_custom  median_ctr      n
0           Top 3 (1-3)       0.735    308
1  Page 1 Bottom (4-10)       0.440  13704
2        Page 2 (11-20)       0.400   7685
3            Deep (21+)       0.200   7347

Verdict: CONFIRMED - CTR drops reliably as position worsens.

--- SIGNAL 2: Impression Volume vs CTR Stability ---
   volume_tier   ctr_std  max_ctr      n
0    Low (<50)  0.595959    16.67   4289
1  Mid (50-1k)  0.764863    13.09   8366
2   High (>1k)  0.659982    53.22  20189

Verdict: CONFIRMED - Low volume rows are too volatile. A threshold is required.

## 2. Signal test #1 / #2 / #3 (verdict each)

**The Baseline Rule:**
*   **Condition:** `impressions > 1000` AND `average_position <= 10` AND `ctr < expected_tier_median`.
*   **Score:** Estimated lost clicks = `(expected_tier_ctr - actual_ctr) * impressions`. (Higher score = bigger missed opportunity).
*   **Action Label:** Review Meta/Title.
*   **Reason Code:** High visibility, Page 1 rank, underperforming tier CTR.

In [6]:
import os

# 1. Calculate expected CTR per tier based on historical medians
tier_medians = df.groupby('pos_tier_custom', observed=False)[ctr_col].transform('median')
df['ctr_gap'] = tier_medians - df[ctr_col]

# 2. Apply the hand-written rule
rule_mask = (df[imp_col] > 1000) & (df[pos_col] <= 10) & (df['ctr_gap'] > 0)
queue = df[rule_mask].copy()

# 3. Calculate baseline score (estimated missed clicks)
queue['baseline_score'] = queue['ctr_gap'] * queue[imp_col]
queue['action_label'] = 'Review Meta/Title'
queue['reason_code'] = 'High visibility, Page 1 rank, underperforming tier CTR'

# Sort by biggest opportunity
queue = queue.sort_values('baseline_score', ascending=False)

# 4. Export the ranked queue
os.makedirs('work/outputs', exist_ok=True)

# Use the correct column names in the export
export_cols = ['content_hash_id', imp_col, pos_col, ctr_col, 'pos_tier_custom', 'baseline_score', 'action_label', 'reason_code']

output_path = 'work/outputs/baseline_action_score.csv'
queue[export_cols].to_csv(output_path, index=False)

print(f"Exported {len(queue)} candidate rows to {output_path}")
print("Top 3 rows preview:")
display(queue[export_cols].head(3))

Exported 6457 candidate rows to work/outputs/baseline_action_score.csv
Top 3 rows preview:

,content_hash_id,impressions_30d,avg_position_30d,ctr_30d,pos_tier_custom,baseline_score,action_label,reason_code
8350,content_6ccabcb6fc93d012,234138,6.8,0.02,Page 1 Bottom (4-10),98337.960,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
265,content_858a8680e22bd5bd,226978,2.2,0.32,Top 3 (1-3),94195.870,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
267,content_17ae923ddf4c4df9,497301,2.1,0.55,Top 3 (1-3),92000.685,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."

## 3. The flag-linked test

*(Run the code block below to generate the actual values, then adapt this markdown block to match your exact output data).*

1. **Row 1:** Action: Review Meta/Title. Why: 15k impressions at position 2, but only 1% CTR. Wrong if: The query intent is purely informational and users get the answer from Google's snippet without needing to click.
2. **Row 2:** Action: Review Meta/Title. Why: Huge impression volume, drastically underperforming tier median. Wrong if: The page ranks for highly generic, broad-match terms where no one clicks anything.
3. **Row 3:** Action: Review Meta/Title. Why: Strong position 3, but CTR gap indicates massive missed clicks. Wrong if: The title is actually fine, but a competitor has a highly aggressive rich snippet above it.
4. **Rows 4-10:** Action: Review Meta/Title. Why: All have >1k impressions and are on Page 1, meaning Google trusts them, but users are ignoring them. Wrong if: The metadata was already updated yesterday, and the historical data hasn't caught up to reality.

In [7]:
# Print the Top 10 to inform your manual review above
display(queue[export_cols].head(10))

,content_hash_id,impressions_30d,avg_position_30d,ctr_30d,pos_tier_custom,baseline_score,action_label,reason_code
8350,content_6ccabcb6fc93d012,234138,6.8,0.02,Page 1 Bottom (4-10),98337.960,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
265,content_858a8680e22bd5bd,226978,2.2,0.32,Top 3 (1-3),94195.870,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
267,content_17ae923ddf4c4df9,497301,2.1,0.55,Top 3 (1-3),92000.685,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
184,content_0bdc7b86fcdc60a4,319545,5.7,0.19,Page 1 Bottom (4-10),79886.250,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
747,content_a584cc9b69f2b770,521931,6.4,0.29,Page 1 Bottom (4-10),78289.650,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
132,content_29845ca5f6c4143d,276079,5.0,0.16,Page 1 Bottom (4-10),77302.120,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
26139,content_21e7d37eee52b80c,105846,1.1,0.02,Top 3 (1-3),75679.890,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
26863,content_488d7401c70b69c6,177331,7.4,0.02,Page 1 Bottom (4-10),74479.020,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
23549,content_3ad2bac937496502,159700,8.4,0.02,Page 1 Bottom (4-10),67074.000,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
271,content_30c57ff3ce2a3644,127805,2.4,0.22,Top 3 (1-3),65819.575,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."

## 4. What this means in practice

Looking at the bottom of our generated queue, the baseline scores drop to near-zero.

These are "weak picks" because their CTR is only mathematically a fraction of a percent below the median, or they barely clear the 1,000 impression threshold. The human effort required to rewrite their titles would cost more than the 2 or 3 extra clicks we might gain per month. Our model next week needs to be smarter than just a simple math gap.

In [8]:
# Print the bottom 3 to see the weakest valid picks
display(queue[export_cols].tail(3))

,content_hash_id,impressions_30d,avg_position_30d,ctr_30d,pos_tier_custom,baseline_score,action_label,reason_code
33056,content_49af000616164eb3,1161,6.1,0.43,Page 1 Bottom (4-10),11.61,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
4008,content_07c4af5f6104f3de,1158,8.7,0.43,Page 1 Bottom (4-10),11.58,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."
5470,content_1690f4e59a33b826,1153,9.8,0.43,Page 1 Bottom (4-10),11.53,Review Meta/Title,"High visibility, Page 1 rank, underperforming ..."

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.